---
title: "R Notebook"
output: html_notebook
---

```{r setup, include = FALSE}
library(tidyverse)
library(plotly)
library(tidytext)
library(spotifyr)
library(scales)
library(geniusr)
source("client.R")
```

```{r, playing, include = FALSE}
my_playlists <- get_my_playlists()
tracks <- get_playlist_tracks(my_playlists[which(my_playlists$name == "2020"),]$id)


ids <- get_track_audio_features(tracks$track.id)
ids <- get_artist_audio_features("muna")

bodies <- search_spotify("bodies muna")$tracks[[2]][1,]$id


count(ids, key_mode, sort = T)

##display image from spotify
magick::image_read("https://i.scdn.co/image/7faf29bbbac031ef6b7127f63a283208bd7ae2dc")

##get discography returns all album data for an artist


#all my saved songs-- can only do ~50 at a time, so would need to loop through 
#and append to get all of these
all_saved <- get_my_saved_tracks(limit = 50)

```

```{r MUNA, include = TRUE}

library(spotifyr)
muna <- get_discography("muna")


# #valence vs energy
# plot_ly(muna) %>% 
#   add_trace(x = ~valence, y = ~energy, color = ~album_name, type = 'scatter', 
#             mode = 'markers', hoverinfo = 'text', text = ~track_name, 
#             colors = c("#DFB1AD", "#8BB7CF"), marker = list(size = 8)) %>% 
#     layout( showlegend = TRUE,
#     xaxis = list(title = "Valence",
#                  zeroline = FALSE, showline = TRUE, linewidth = 3,
#                  ticks = "outside", ticklen = 10, tickwidth = 3,
#                  showgrid = FALSE),
#     yaxis = list(title = "Energy",
#                  zeroline = FALSE, showline = TRUE, linewidth = 3,
#                  ticks = "outside", ticklen = 10, tickwidth = 3,
#                  showgrid = FALSE)
#     )

lyrics <- muna$lyrics
names(lyrics) <- muna$track_name

nrc <- get_sentiments("nrc")
munalyrics <- bind_rows(lyrics, .id = "trackname") %>% 
  unnest_tokens(output = word, input = lyric) %>% 
  group_by(trackname) %>%
  mutate(wordcount = n()) %>%
  ungroup()


#all stw lyrics analysis
stwlyrics <- lyrics[1:12]
abtulyrics <- lyrics[13:24]
stw <- bind_rows(stwlyrics, .id = "trackname") %>% 
  unnest_tokens(output = word, input = lyric) %>% 
  group_by(trackname) %>% 
  mutate(wordcount = n()) %>% 
  ungroup() 

abtu <- bind_rows(abtulyrics, .id = "trackname") %>% 
  unnest_tokens(output = word, input = lyric) %>% 
    group_by(trackname) %>% 
  mutate(wordcount = n()) %>% 
  ungroup() 


lyrics <- bind_rows(list(stw, abtu), .id = "album") %>% group_by(trackname)
lyrics$album <- ifelse(lyrics$album == 1, "Saves the World", "About U")

#count pos vs neg words by song
# track_sent <- lyrics %>% 
#   left_join(bing, by = 'word') %>%  
#   count(trackname, sentiment, name = 'tally') %>% 
#   group_by(trackname) %>% 
#   mutate(pct = tally/sum(tally) * 100)


track_sent <- lyrics %>% 
  anti_join(stop_words, by = 'word') %>%
  left_join(nrc, by = 'word') %>% 
  count(trackname, sentiment, name = 'tally') %>%
  group_by(trackname) %>%
  mutate(pct = tally/sum(tally))


#gloom_index
sadtracks <- track_sent %>% 
  filter(sentiment == 'sadness') %>% 
  right_join(lyrics %>% filter(row_number() == 1), by = "trackname") %>% 
  left_join(muna, by = c("trackname" = "track_name")) %>%
  mutate_at(c('pct', 'wordcount'), funs(ifelse(is.na(.), 0, .))) %>% 
  mutate(lyrical_density = wordcount / duration_ms * 1000,
         gloom_index = ((1 - valence) + (pct*(1+lyrical_density))) / 2) %>% 
  mutate(dist = sqrt((energy)^2 + (gloom_index/max(sadtracks$gloom_index))^2))


sadtracks %>%
  select(gloom_index, dist, trackname) %>%
	arrange(desc(dist)) %>%
	head(10)

#valence/energy for sad bops
# muna_plot <- plot_ly(sadtracks) %>% 
#   add_trace(x = ~gloom_index/max(gloom_index), y = ~energy, color = ~album_name, type = 'scatter', 
#             mode = 'markers', hoverinfo = 'text', 
#             text = paste("Track: ", sadtracks$trackname,
#                          "<br>Album: ", sadtracks$album_name,
#                                 "<br>Gloom Index: ", round(sadtracks$gloom_index, 3),
#                                 "<br>Energy: ", sadtracks$energy, 
#                                 "<br>Sad Bop Index: ", round(sadtracks$dist, 3)
#                                 ),
#             colors = c("#DFB1AD", "#8BB7CF"), marker = list(size = 10)) %>% 
#     layout( showlegend = TRUE, legend = list(orientation = 'v',  size = 12),
#             title = "<b>MUNA's Catalog of Sad Bops <br> by Album</b>", 
#             titlefont = list(size = 25,family = "PT Sans Narrow"), 
#     xaxis = list(title = "<b>Sad (norm. gloom index)</b>", range = c(0, 1.1),
#                  titlefont = list(family = "PT Sans Narrow", size = 18),
#                  zeroline = FALSE, showline = TRUE, linewidth = 3,
#                  ticks = "outside", ticklen = 10, tickwidth = 3,
#                  showgrid = FALSE),
#     yaxis = list(title = "<b>Bop (energy)</b>", range = c(0, 1.1),
#                  titlefont = list(family = "PT Sans Narrow", size = 18),
#                  zeroline = FALSE, showline = TRUE, linewidth = 3,
#                  ticks = "outside", ticklen = 10, tickwidth = 3,
#                  showgrid = FALSE),
#     margin = list(t = 80, b = 50)
#     )
# 
# api_create(muna_plot, filename = "Muna_catalog")

# grwords <- tibble(c("i", "me", "myself", "i've", "i'll", "i'd", "we","you're", "you've", "you", "your", "you'd", "yourself"))
# grwords$who <- "I"
# grwords$who[7] <- "we"
# grwords$who[8:13] <- "you"
# 
# growth <- lyrics %>% 
#   inner_join(grwords) %>%
#   count(who, album)

#key analysis
# keys <- muna %>% count(key_mode, album_name)
# keys2 <- muna %>%  count(mode_name, album_name)

```

```{r sad bops, echo = TRUE}
#figure out how to get lyrics from genius api
sadbops <- get_playlist_audio_features("spotify","37i9dQZF1DWZUAeYvs88zc")

sadboplyrics <- list()

#run in console
for(i in seq_along(sadbops$track.name)){
  test <- sadbops[i,]
  artist <- test$track.artists[[1]]$name[1]
  title <- test$track.name
  results <- search_song(paste(title, artist))
  print(results)
  print(paste(artist, title))
  choice <- as.integer(readline())
  ids <- results[choice,]$song_id
  testlyr <- get_lyrics_id(ids) 
}

sadbopwords <- bind_rows(sadboplyrics) %>% 
  unnest_tokens(output = word, input = line) %>% 
  group_by(song_name) %>% 
  mutate(wordcount = n()) %>% 
  ungroup() 

tracks <- sadbopwords %>% group_by(song_name) %>% 
  filter(row_number() == 1)

sadbopsent <- sadbopwords %>% 
  left_join(nrc, by = 'word') %>% 
  anti_join(stop_words, by = 'word') %>%
  count(song_name, sentiment, name = 'tally') %>%
  group_by(song_name) %>%
  mutate(pct = tally/sum(tally)) %>%
  filter(sentiment == "sadness") %>%
  right_join(tracks, by = 'song_name') %>%
  bind_cols(sadbops) %>%
  filter(!is.na(sentiment)) %>%
  mutate(lyrical_density = (wordcount / track.duration_ms) * 1000,
         gloom_index = ((1 - valence) + (pct*(1+lyrical_density))) / 2) %>%
  mutate(dist = sqrt((energy)^2 + (gloom_index/max(sadbopsent$gloom_index))^2))

sadbopsent %>% 
  select(song_name, gloom_index, dist) %>% 
  arrange(desc(dist))

plot_ly(sadbopsent) %>% 
  add_trace(x = ~gloom_index/max(gloom_index), y = ~energy/max(energy), type = 'scatter', 
            mode = 'markers', hoverinfo = 'text', 
            text = paste("Track: ", sadbopsent$song_name,
                                "<br>Gloom Index: ", round(sadbopsent$gloom_index, 3),
                                "<br>Energy: ", sadtracks$energy, 
                                "<br>Sad Bop Index: ", round(sadbopsent$dist, 3)
                                ),
            marker = list(size = 8, color = "#A5A2A2")) %>% 
    layout( showlegend = FALSE,
    xaxis = list(title = "Sad", range = c(0,1.1), 
                 zeroline = FALSE, showline = TRUE, linewidth = 3,
                 ticks = "outside", ticklen = 10, tickwidth = 3, dtick = 0.1,
                 showgrid = FALSE),
    yaxis = list(title = "Bop", range = c(0,1.1),
                 zeroline = FALSE, showline = TRUE, linewidth = 3,
                 ticks = "outside", ticklen = 10, tickwidth = 3, dtick = 0.1,
                 showgrid = FALSE)
    )

```

```{r, all compare}

cleansadbops <- sadbopsent %>% 
  select(song_name, artist_name, energy, gloom_index)

sadtracks$artist <- "MUNA"

cleansadmuna <- sadtracks %>% 
  select(trackname, artist, energy, gloom_index)

colnames(cleansadmuna) <- c(colnames(cleansadbops))

cleansadbops <- cleansadbops %>% 
  bind_rows(cleansadmuna) %>% 
  mutate(dist = sqrt((energy)^2 + (gloom_index/max(cleansadbops$gloom_index))^2))

cleansadbops$color <- ifelse(cleansadbops$artist_name == "MUNA", "MUNA", "Spotify's Sad Bops")

print(cleansadbops %>% arrange(desc(dist)))

sadbop_plot <- plot_ly(cleansadbops) %>% 
  add_trace(cleansadbops[c(1:72),], x = ~gloom_index/max(gloom_index), y = ~energy, type = 'scatter', 
            mode = 'markers', hoverinfo = 'text', color = ~color, colors = c("#DFB1AD", "#A5A2A2"),
            text = paste("Track: ", cleansadbops$song_name,
                         "<br>Artist: ", cleansadbops$artist_name,
                                "<br>Gloom Index: ", round(cleansadbops$gloom_index, 3),
                                "<br>Energy: ", cleansadbops$energy, 
                                "<br>Sad Bop Index: ", round(cleansadbops$dist, 3)
                                ),
            marker = list(size = 10)) %>% 
  # add_trace(x = c(0:2), y = 0.5, type = 'scatter', mode = 'line', 
  #           line = list(size = 5, color = 'black', dash = 'dash')) %>% 
  #   add_trace(x = 0.5, y = c(0:2), type = 'scatter', mode = 'line', 
  #           line = list(size = 5, color = 'black', dash = 'dash')) %>% 
    layout( showlegend = TRUE, title = "<b>Sad Bops</b>", titlefont = list(size = 25,family = "PT Sans Narrow"),
    xaxis = list(title = "<b>Sad (norm. gloom index)</b>", range = c(0,1.05), titlefont = list(size = 18,family = "PT Sans Narrow"),
                 zeroline = FALSE, showline = TRUE, linewidth = 3,
                 ticks = "outside", ticklen = 10, tickwidth = 3, dtick = 0.1,
                 showgrid = FALSE),
    yaxis = list(title = "<b>Bop (energy)</b>", range = c(0,1.05), titlefont = list(size = 18,family = "PT Sans Narrow"),
                 zeroline = FALSE, showline = TRUE, linewidth = 3,
                 ticks = "outside", ticklen = 10, tickwidth = 3, dtick = 0.1,
                 showgrid = FALSE), 
    margin = list(t = 80, b = 50)
    )

api_create(sadbop_plot, filename = "All_sadbops")


```

```{r}
ggplot(filter(track_sent, !is.na(sentiment), trackname == "Stayaway"),aes(x = trackname, y = tally, fill = sentiment)) + 
  geom_bar(position = "fill",stat = "identity") + 
  scale_y_continuous(labels = percent_format()) +
  coord_flip() + theme_classic() +
  labs(x = "", 
       y = "", 
       colour = "Sentiment") +
  theme(legend.position="bottom")
  
```