---
title: "Sad_Bop_2.0"
author: "B Rose"
date: "8/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tidytext)
library(spotifyr)
library(scales)
library(gt)
library(webshot)
source("client.R")
```

Building and cleaning the dataset
```{r data, include = TRUE}
muna <- get_discography("muna")
lyrics <- muna$lyrics
names(lyrics) <- muna$track_name

nrc <- get_sentiments("nrc")
munalyrics <- bind_rows(lyrics, .id = "trackname") %>% 
  unnest_tokens(output = word, input = lyric) %>% 
  group_by(trackname) %>%
  mutate(wordcount = n()) %>%
  ungroup()


#all stw lyrics analysis
stwlyrics <- lyrics[1:12]
abtulyrics <- lyrics[13:24]
stw <- bind_rows(stwlyrics, .id = "trackname") %>% 
  unnest_tokens(output = word, input = lyric) %>% 
  group_by(trackname) %>% 
  mutate(wordcount = n()) %>% 
  ungroup() 

abtu <- bind_rows(abtulyrics, .id = "trackname") %>% 
  unnest_tokens(output = word, input = lyric) %>% 
    group_by(trackname) %>% 
  mutate(wordcount = n()) %>% 
  ungroup() 


lyrics <- bind_rows(list(stw, abtu), .id = "album") %>% group_by(trackname)
lyrics$album <- ifelse(lyrics$album == 1, "Saves the World", "About U")


track_sent <- lyrics %>% 
  anti_join(stop_words, by = 'word') %>%
  left_join(nrc, by = 'word') %>% 
  count(trackname, sentiment, name = 'tally') %>%
  group_by(trackname) %>%
  mutate(pct = tally/sum(tally))

sadtracks <- track_sent %>% 
  filter(sentiment == 'sadness') %>% 
  right_join(lyrics %>% filter(row_number() == 1), by = "trackname") %>% 
  left_join(muna, by = c("trackname" = "track_name")) %>%
  mutate_at(c('pct', 'wordcount'), funs(ifelse(is.na(.), 0, .))) %>% 
  mutate(lyrical_density = wordcount / duration_ms * 1000,
         gloom_index = ((1 - valence) + (pct*(1+lyrical_density))) / 2) %>% 
  ungroup()

sadtracks %>% 
  mutate(dist = sqrt((energy)^2 + (gloom_index/max(sadtracks$gloom_index))^2)) -> sadtracks

sadtracks %>%
  select(gloom_index, dist, trackname) %>%
	arrange(desc(dist)) %>%
	head(10)

```

Building the table
```{r table}
#bar plot function
bar_chart <- function(value, color = "black", display_value = NULL){
  # Choose to display percent of total
  if (is.null(display_value)) {
    display_value <- "&nbsp;"
  } else {
    display_value <- display_value
  }
  # paste color and value into the html string
  glue::glue("<span style=\"display: inline-block; direction: ltr; border-radius: 4px; padding-right: 2px; background-color: {color}; color: {color}; width: {value}%\"> {display_value} </span>")
}

bar_dist <- sadtracks %>% 
  select(album, trackname, gloom_index, energy, dist, track_number) %>% 
  # arrange(track_number) %>%
  mutate(
    n_gloom = round(gloom_index/max(gloom_index), digits = 3),
    bar = round(dist/max(dist)*100, digits = 3),
    # color = "#958eae",
    color = "#9bb48A",
    bar_chart = bar_chart(bar, color = color),
    bar_chart = map(bar_chart, ~gt::html(as.character(.x)))) %>% 
  select(album, trackname, n_gloom, energy, dist, bar_chart, track_number)

bar_dist %>%
  arrange(track_number) %>% 
  select(-track_number) %>% 
  ##table code
  gt(groupname_col = "album") %>%
  tab_stubhead("label") %>% 
  #format numbers
  fmt_number(columns = 3:5, decimals = 3) %>% 
  #column width
  cols_width(
    vars(album) ~ px(200), 
    vars(trackname) ~ px(250),
    vars(dist) ~ px(110),
    vars(bar_chart) ~ px(120),
    c("n_gloom", "energy") ~ px(110) 
  ) %>% 
  #gradient colors
  data_color(
    columns = vars(n_gloom), 
    colors = scales::col_numeric(
      c("#E9F7FF","#9BCAE3","#4D9CC6"),
      domain = NULL
    )
  ) %>% 
  data_color(
    columns = vars(energy), 
    colors = scales::col_numeric(
      # c("#FFE9EE","#EEB4C2","#DD7F96"),
      c("#FFF6CE","#F4E18E","#E9CC4E"),
      domain = NULL
    )
  ) %>% 
  #rename columns
  cols_label(
    trackname = "", 
    n_gloom = "Norm. Gloom Index",
    energy = "Energy",
    dist = "Sad Bop Character",
    bar_chart = ""
  ) %>% 
  
  #format column/group labels  
  tab_style(
    style = list(
      cell_text(color = "black", font = "Helvetica", weight = "bold")
      ),
    locations = list(
      cells_row_groups(), 
      cells_column_labels(everything())
    )
  ) %>% 
  #align columns
  cols_align(align = "right",
             columns = TRUE) %>% 
  cols_align(align = "left",
             columns = vars(album, trackname, bar_chart)) %>% 
  #header
  tab_header(
    title = md("**MUNA's Sad Bop Discography**"),
    subtitle = "Quantifying the sad bop using lyrical and sonic attributes of songs
                from two MUNA albums."
  ) %>% 
  #source note
  tab_source_note(md("**Source**: @baileysutton <br> 
                    **Data**: Spotify <i>via</i> spotifyr @_RCharlie | **Inspiration**: @thomas_mock")) %>% 
  #theme
  tab_options(
    heading.align = "left",
    heading.subtitle.font.size = 17,
    heading.title.font.size = 26,
    heading.title.font.weight = "bold",
    heading.border.bottom.color = "white",
    heading.border.bottom.width = px(20),
    row_group.border.top.color = "black", 
    row_group.border.top.width = px(2),
    row_group.border.bottom.color = "black",
    column_labels.border.top.color = "white",
    column_labels.border.top.width = px(2),
    column_labels.border.bottom.color = "black",
    column_labels.border.bottom.width= px(2),
    table_body.hlines.color = "white",
    table.border.bottom.color = "white",
    table.border.bottom.width = px(2),
    table.border.top.color = "white",
    table.border.top.width = px(8)
  ) -> table
```

Save the table
```{r save} 
gtsave(table, "sadbop_table.html")
gtsave(table, "sadbop_table.png", zoom = 3)
```